.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/actions.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/actions.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.sms_calendar\&.actions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.main_calendar_action\fP (str calendar_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.new_task_action\fP (str calendar_id, int year, int month)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.edit_task_action\fP (str calendar_id, int year, int month, int day, int task_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.update_task_action\fP (str calendar_id, str year, str month, str day, str task_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.save_task_action\fP (str calendar_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.delete_task_action\fP (str calendar_id, str year, str month, str day, str task_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.update_task_day_action\fP (str calendar_id, str year, str month, str day, str task_id)"
.br
.ti -1c
.RI "Response \fBsms\&.sms_calendar\&.actions\&.hide_repetition_task_instance_action\fP (str calendar_id, str year, str month, str day, str task_id)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
