.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/app_utils.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/app_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.sms_calendar\&.app_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBsms\&.sms_calendar\&.app_utils\&.previous_month_link\fP (int year, int month)"
.br
.ti -1c
.RI "str \fBsms\&.sms_calendar\&.app_utils\&.next_month_link\fP (int year, int month)"
.br
.ti -1c
.RI "str \fBsms\&.sms_calendar\&.app_utils\&.new_session_id\fP ()"
.br
.ti -1c
.RI "bool \fBsms\&.sms_calendar\&.app_utils\&.is_session_valid\fP (str session_id)"
.br
.ti -1c
.RI "None \fBsms\&.sms_calendar\&.app_utils\&.add_session\fP (str session_id, str username)"
.br
.ti -1c
.RI "str \fBsms\&.sms_calendar\&.app_utils\&.get_session_username\fP (str session_id)"
.br
.ti -1c
.RI "str \fBsms\&.sms_calendar\&.app_utils\&.task_details_for_markup\fP (str details)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms\&.sms_calendar\&.app_utils\&.cache\fP = SimpleCache()"
.br
.ti -1c
.RI "string \fBsms\&.sms_calendar\&.app_utils\&.URLS_REGEX_PATTERN\fP = r'((?:(?:https?):\\/\\/)?[\\w/\\\-?=%\&.]+\\\&.[\\w/\\\-?=%\&.&]+)'"
.br
.ti -1c
.RI "string \fBsms\&.sms_calendar\&.app_utils\&.DECORATED_URL_FORMAT\fP = '<a href=\\'{}\\' target=\\'_blank\\'>{}</a>'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
