.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/migrations/versions Directory Reference" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/migrations/versions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBf1c90aad993e_\&.py\fP"
.br
.in -1c
