.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS Directory Reference" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmigrations\fP"
.br
.ti -1c
.RI "directory \fBsms\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrun\&.py\fP"
.br
.in -1c
