.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar Directory Reference" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBactions\&.py\fP"
.br
.ti -1c
.RI "file \fBapp_utils\&.py\fP"
.br
.ti -1c
.RI "file \fBcalendar_data\&.py\fP"
.br
.ti -1c
.RI "file \fBconstants\&.py\fP"
.br
.ti -1c
.RI "file \fBgregorian_calendar\&.py\fP"
.br
.ti -1c
.RI "file \fBroutes\&.py\fP"
.br
.ti -1c
.RI "file \fBuwsgi\&.py\fP"
.br
.in -1c
