.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/constants.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/constants.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.sms_calendar\&.constants\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsms\&.sms_calendar\&.constants\&.SESSION_ID\fP = 'sid'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
