.TH "f1c90aad993e_" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f1c90aad993e_
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupgrade\fP ()"
.br
.ti -1c
.RI "def \fBdowngrade\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBrevision\fP = 'f1c90aad993e'"
.br
.ti -1c
.RI "\fBdown_revision\fP = None"
.br
.ti -1c
.RI "\fBbranch_labels\fP = None"
.br
.ti -1c
.RI "\fBdepends_on\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
empty message

Revision ID: f1c90aad993e
Revises: 
Create Date: 2019-12-28 18:29:15.127104
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def f1c90aad993e_\&.downgrade ()"

.PP
Definition at line 135 of file f1c90aad993e_\&.py\&.
.SS "def f1c90aad993e_\&.upgrade ()"

.PP
Definition at line 19 of file f1c90aad993e_\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "f1c90aad993e_\&.branch_labels = None"

.PP
Definition at line 15 of file f1c90aad993e_\&.py\&.
.SS "f1c90aad993e_\&.depends_on = None"

.PP
Definition at line 16 of file f1c90aad993e_\&.py\&.
.SS "f1c90aad993e_\&.down_revision = None"

.PP
Definition at line 14 of file f1c90aad993e_\&.py\&.
.SS "string f1c90aad993e_\&.revision = 'f1c90aad993e'"

.PP
Definition at line 13 of file f1c90aad993e_\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
