.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/migrations/versions/f1c90aad993e_.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/migrations/versions/f1c90aad993e_.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBf1c90aad993e_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBf1c90aad993e_\&.upgrade\fP ()"
.br
.ti -1c
.RI "def \fBf1c90aad993e_\&.downgrade\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBf1c90aad993e_\&.revision\fP = 'f1c90aad993e'"
.br
.ti -1c
.RI "\fBf1c90aad993e_\&.down_revision\fP = None"
.br
.ti -1c
.RI "\fBf1c90aad993e_\&.branch_labels\fP = None"
.br
.ti -1c
.RI "\fBf1c90aad993e_\&.depends_on\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
