.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/gregorian_calendar.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/gregorian_calendar.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsms\&.sms_calendar\&.gregorian_calendar\&.GregorianCalendar\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.sms_calendar\&.gregorian_calendar\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
