.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/errors/handlers.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/errors/handlers.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.errors\&.handlers\fP"
.br
.ti -1c
.RI " \fBERRORS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsms\&.errors\&.handlers\&.error_404\fP (error)"
.br
.RI "Method handling error 404\&. "
.ti -1c
.RI "def \fBsms\&.errors\&.handlers\&.error_403\fP (error)"
.br
.RI "Method handling error 403\&. "
.ti -1c
.RI "def \fBsms\&.errors\&.handlers\&.error_500\fP (error)"
.br
.RI "Method handling error 500\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms\&.errors\&.handlers\&.errors\fP = Blueprint('errors', __name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
