.TH "MAIN" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MAIN
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The '\fBMAIN\fP' package contains all routes, forms, and utils that aren't specific for someone and doesn't require login\&.
.PP
Mainly, the '\fBMAIN\fP' package contain blog-related routes and forms such as 'Home', 'News', 'Achievements', etc\&.\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
