.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/models.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/models.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsms\&.models\&.User\fP"
.br
.RI "Describes the fields for administrators\&. "
.ti -1c
.RI "class \fBsms\&.models\&.UserView\fP"
.br
.RI "Describes the fields and behavior of the UserModel on the administrator dashboard\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Students\fP"
.br
.RI "Describes the fields for students\&. "
.ti -1c
.RI "class \fBsms\&.models\&.StudentsView\fP"
.br
.RI "Describes the fields and behavior of the StudentsModel on the administrator dashboard\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Staff\fP"
.br
.RI "Describes the fields for staff\&. "
.ti -1c
.RI "class \fBsms\&.models\&.StaffView\fP"
.br
.RI "Describes the fields and behavior of the StaffModel on the administrator dashboard\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Subjects\fP"
.br
.RI "Describes the fields for subjects\&. "
.ti -1c
.RI "class \fBsms\&.models\&.PeriodicalAssessment\fP"
.br
.RI "Describes the fields for periodical assessment\&. "
.ti -1c
.RI "class \fBsms\&.models\&.ABLLS_Assessment\fP"
.br
.RI "Describes the fields for ABLLS assessment\&. "
.ti -1c
.RI "class \fBsms\&.models\&.News\fP"
.br
.RI "Describes the fields for news\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Achievements\fP"
.br
.RI "Describes the fields for achievements\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Team\fP"
.br
.RI "Describes the fields for team\&. "
.ti -1c
.RI "class \fBsms\&.models\&.Post\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsms\&.models\&.load_user\fP (user_id)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms\&.models\&.students_subjects\fP"
.br
.RI "Many to many relationship between students and subjects\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
