.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/users/routes.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/users/routes.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.users\&.routes\fP"
.br
.ti -1c
.RI " \fBUSERS\fP"
.br
.RI "The '\fBUSERS\fP' package contains all routes, forms, and utils that are specific for users according to their roles and requires login\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.register\fP ()"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.login\fP ()"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.logout\fP ()"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.account\fP ()"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.user_posts\fP (username)"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.reset_request\fP ()"
.br
.ti -1c
.RI "def \fBsms\&.users\&.routes\&.reset_token\fP (token)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms\&.users\&.routes\&.users\fP = Blueprint('users', __name__)"
.br
.ti -1c
.RI "\fBsms\&.users\&.routes\&.methods\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
