.TH "sms.sms_calendar.calendar_data" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.sms_calendar.calendar_data
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalendarData\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBKEY_TASKS\fP = 'tasks'"
.br
.ti -1c
.RI "string \fBKEY_USERS\fP = 'users'"
.br
.ti -1c
.RI "string \fBKEY_NORMAL_TASK\fP = 'normal'"
.br
.ti -1c
.RI "string \fBKEY_REPETITIVE_TASK\fP = 'repetition'"
.br
.ti -1c
.RI "string \fBKEY_REPETITIVE_HIDDEN_TASK\fP = 'hidden_repetition'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string sms\&.sms_calendar\&.calendar_data\&.KEY_NORMAL_TASK = 'normal'"

.PP
Definition at line 14 of file calendar_data\&.py\&.
.SS "string sms\&.sms_calendar\&.calendar_data\&.KEY_REPETITIVE_HIDDEN_TASK = 'hidden_repetition'"

.PP
Definition at line 16 of file calendar_data\&.py\&.
.SS "string sms\&.sms_calendar\&.calendar_data\&.KEY_REPETITIVE_TASK = 'repetition'"

.PP
Definition at line 15 of file calendar_data\&.py\&.
.SS "string sms\&.sms_calendar\&.calendar_data\&.KEY_TASKS = 'tasks'"

.PP
Definition at line 12 of file calendar_data\&.py\&.
.SS "string sms\&.sms_calendar\&.calendar_data\&.KEY_USERS = 'users'"

.PP
Definition at line 13 of file calendar_data\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
