.TH "sms.main.forms" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.main.forms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewsForm\fP"
.br
.RI "\fBNewsForm\fP class specifies the fields for news published\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
