.TH "sms.errors.handlers" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.errors.handlers
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBerror_404\fP (error)"
.br
.RI "Method handling error 404\&. "
.ti -1c
.RI "def \fBerror_403\fP (error)"
.br
.RI "Method handling error 403\&. "
.ti -1c
.RI "def \fBerror_500\fP (error)"
.br
.RI "Method handling error 500\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBerrors\fP = Blueprint('errors', __name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def sms\&.errors\&.handlers\&.error_403 ( error)"

.PP
Method handling error 403\&. 
.PP
\fBParameters\fP
.RS 4
\fI403\fP The error value 
.RE
.PP

.PP
Definition at line 21 of file handlers\&.py\&.
.SS "def sms\&.errors\&.handlers\&.error_404 ( error)"

.PP
Method handling error 404\&. 
.PP
\fBParameters\fP
.RS 4
\fI404\fP The error value 
.RE
.PP

.PP
Definition at line 14 of file handlers\&.py\&.
.SS "def sms\&.errors\&.handlers\&.error_500 ( error)"

.PP
Method handling error 500\&. 
.PP
\fBParameters\fP
.RS 4
\fI500\fP The error value 
.RE
.PP

.PP
Definition at line 28 of file handlers\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "sms\&.errors\&.handlers\&.errors = Blueprint('errors', __name__)"

.PP
Definition at line 9 of file handlers\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
