.TH "sms.users.routes" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.users.routes
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBregister\fP ()"
.br
.ti -1c
.RI "def \fBlogin\fP ()"
.br
.ti -1c
.RI "def \fBlogout\fP ()"
.br
.ti -1c
.RI "def \fBaccount\fP ()"
.br
.ti -1c
.RI "def \fBuser_posts\fP (username)"
.br
.ti -1c
.RI "def \fBreset_request\fP ()"
.br
.ti -1c
.RI "def \fBreset_token\fP (token)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBusers\fP = Blueprint('users', __name__)"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def sms\&.users\&.routes\&.account ()"

.PP
Definition at line 58 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.login ()"

.PP
Definition at line 35 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.logout ()"

.PP
Definition at line 51 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.register ()"

.PP
Definition at line 18 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.reset_request ()"

.PP
Definition at line 88 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.reset_token ( token)"

.PP
Definition at line 101 of file routes\&.py\&.
.SS "def sms\&.users\&.routes\&.user_posts ( username)"

.PP
Definition at line 78 of file routes\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "sms\&.users\&.routes\&.methods"

.PP
Definition at line 17 of file routes\&.py\&.
.SS "sms\&.users\&.routes\&.users = Blueprint('users', __name__)"

.PP
Definition at line 14 of file routes\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
