.TH "sms.users.forms.RequestResetForm" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.users.forms.RequestResetForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits FlaskForm\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBvalidate_email\fP (self, \fBemail\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBemail\fP = StringField('Email', validators=[DataRequired(), Email()])"
.br
.ti -1c
.RI "\fBsubmit\fP = SubmitField('Request Password Reset')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file forms\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def sms\&.users\&.forms\&.RequestResetForm\&.validate_email ( self,  email)"

.PP
Definition at line 64 of file forms\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "sms\&.users\&.forms\&.RequestResetForm\&.email = StringField('Email', validators=[DataRequired(), Email()])\fC [static]\fP"

.PP
Definition at line 61 of file forms\&.py\&.
.SS "sms\&.users\&.forms\&.RequestResetForm\&.submit = SubmitField('Request Password Reset')\fC [static]\fP"

.PP
Definition at line 62 of file forms\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
