.TH "sms.models.Subjects" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.models.Subjects \- Describes the fields for subjects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP = db\&.Column(db\&.Integer, primary_key=True)"
.br
.ti -1c
.RI "\fBname\fP = db\&.Column(db\&.String(100), nullable=False)"
.br
.ti -1c
.RI "\fBdescription\fP = db\&.Column(db\&.Text(), unique=False, nullable=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the fields for subjects\&. 
.PP
Definition at line 248 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "sms\&.models\&.Subjects\&.description = db\&.Column(db\&.Text(), unique=False, nullable=True)\fC [static]\fP"

.PP
Definition at line 252 of file models\&.py\&.
.SS "sms\&.models\&.Subjects\&.id = db\&.Column(db\&.Integer, primary_key=True)\fC [static]\fP"

.PP
Definition at line 250 of file models\&.py\&.
.SS "sms\&.models\&.Subjects\&.name = db\&.Column(db\&.String(100), nullable=False)\fC [static]\fP"

.PP
Definition at line 251 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
