.TH "sms.sms_calendar" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.sms_calendar
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBactions\fP"
.br
.ti -1c
.RI " \fBapp_utils\fP"
.br
.ti -1c
.RI " \fBcalendar_data\fP"
.br
.ti -1c
.RI " \fBconstants\fP"
.br
.ti -1c
.RI " \fBgregorian_calendar\fP"
.br
.ti -1c
.RI " \fBroutes\fP"
.br
.ti -1c
.RI " \fBuwsgi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
