.TH "sms.sms_calendar.uwsgi" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.sms_calendar.uwsgi
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBapp\fP = flask_app\&.create_app()"
.br
.ti -1c
.RI "\fBdebug\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sms\&.sms_calendar\&.uwsgi\&.app = flask_app\&.create_app()"

.PP
Definition at line 4 of file uwsgi\&.py\&.
.SS "sms\&.sms_calendar\&.uwsgi\&.debug"

.PP
Definition at line 7 of file uwsgi\&.py\&.
.SS "sms\&.sms_calendar\&.uwsgi\&.host"

.PP
Definition at line 7 of file uwsgi\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
