.TH "sms.posts.forms.PostForm" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.posts.forms.PostForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits FlaskForm\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP = StringField('Title', validators=[DataRequired()])"
.br
.ti -1c
.RI "\fBcontent\fP = TextAreaField('Content', validators=[DataRequired()])"
.br
.ti -1c
.RI "\fBsubmit\fP = SubmitField('Post')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file forms\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "sms\&.posts\&.forms\&.PostForm\&.content = TextAreaField('Content', validators=[DataRequired()])\fC [static]\fP"

.PP
Definition at line 7 of file forms\&.py\&.
.SS "sms\&.posts\&.forms\&.PostForm\&.submit = SubmitField('Post')\fC [static]\fP"

.PP
Definition at line 8 of file forms\&.py\&.
.SS "sms\&.posts\&.forms\&.PostForm\&.title = StringField('Title', validators=[DataRequired()])\fC [static]\fP"

.PP
Definition at line 6 of file forms\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
