.TH "sms.models.StudentsView" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.models.StudentsView \- Describes the fields and behavior of the StudentsModel on the administrator dashboard\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelView\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpage_size\fP = 20"
.br
.ti -1c
.RI "bool \fBcan_view_details\fP = True"
.br
.ti -1c
.RI "list \fBcolumn_list\fP = ['username','first_name','middle_name','last_name','mother_name','email','phone_number','address','image_file','date_created','date_updated']"
.br
.ti -1c
.RI "list \fBcolumn_exclude_list\fP = ['']"
.br
.ti -1c
.RI "list \fBform_columns\fP"
.br
.ti -1c
.RI "dictionary \fBform_widget_args\fP"
.br
.ti -1c
.RI "list \fBcolumn_searchable_list\fP = ['username']"
.br
.ti -1c
.RI "string \fBcolumn_default_sort\fP = 'username'"
.br
.ti -1c
.RI "list \fBcolumn_sortable_list\fP = ['username','date_created','date_updated']"
.br
.ti -1c
.RI "bool \fBcan_export\fP = True"
.br
.ti -1c
.RI "list \fBcolumn_filters\fP"
.br
.ti -1c
.RI "list \fBcolumn_export_list\fP = ['name', 'first_name', 'middle_name', 'last_name', 'mother_name','address', 'phone_number','date_created', 'date_updated']"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the fields and behavior of the StudentsModel on the administrator dashboard\&. 
.PP
Definition at line 147 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "bool sms\&.models\&.StudentsView\&.can_export = True\fC [static]\fP"

.PP
Definition at line 172 of file models\&.py\&.
.SS "bool sms\&.models\&.StudentsView\&.can_view_details = True\fC [static]\fP"

.PP
Definition at line 149 of file models\&.py\&.
.SS "string sms\&.models\&.StudentsView\&.column_default_sort = 'username'\fC [static]\fP"

.PP
Definition at line 170 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_exclude_list = ['']\fC [static]\fP"

.PP
Definition at line 152 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_export_list = ['name', 'first_name', 'middle_name', 'last_name', 'mother_name','address', 'phone_number','date_created', 'date_updated']\fC [static]\fP"

.PP
Definition at line 179 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_filters\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  [
        FilterEqual(column=User\&.username, name = 'Name'),
        FilterNotEqual(column=User\&.username, name = 'Name'),
        FilterLike(column=User\&.username, name='Name'),
        FilterNotLike(column=User\&.username, name='Name'),
    ]
.fi
.PP
Definition at line 173 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_list = ['username','first_name','middle_name','last_name','mother_name','email','phone_number','address','image_file','date_created','date_updated']\fC [static]\fP"

.PP
Definition at line 150 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_searchable_list = ['username']\fC [static]\fP"

.PP
Definition at line 169 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.column_sortable_list = ['username','date_created','date_updated']\fC [static]\fP"

.PP
Definition at line 171 of file models\&.py\&.
.SS "list sms\&.models\&.StudentsView\&.form_columns\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ['username', 'first_name', 'middle_name', 'last_name', 'mother_name',
    'email', 'password','phone_number', 'address']
.fi
.PP
Definition at line 153 of file models\&.py\&.
.SS "dictionary sms\&.models\&.StudentsView\&.form_widget_args\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  {
        'date_updated': {
            'disabled': True
        },
        'date_created': {
            'disabled': True
        },
        'image_file':{
            'disabled': True
        }
    }
.fi
.PP
Definition at line 155 of file models\&.py\&.
.SS "int sms\&.models\&.StudentsView\&.page_size = 20\fC [static]\fP"

.PP
Definition at line 148 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
