.TH "sms.sms_calendar.constants" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.sms_calendar.constants
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBSESSION_ID\fP = 'sid'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string sms\&.sms_calendar\&.constants\&.SESSION_ID = 'sid'"

.PP
Definition at line 2 of file constants\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
