.TH "sms.models.ABLLS_Assessment" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.models.ABLLS_Assessment \- Describes the fields for ABLLS assessment\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP = db\&.Column(db\&.Integer, primary_key=True)"
.br
.ti -1c
.RI "\fBskills\fP = db\&.Column(db\&.String(), nullable=False)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the fields for ABLLS assessment\&. 
.PP
Definition at line 268 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "sms\&.models\&.ABLLS_Assessment\&.id = db\&.Column(db\&.Integer, primary_key=True)\fC [static]\fP"

.PP
Definition at line 270 of file models\&.py\&.
.SS "sms\&.models\&.ABLLS_Assessment\&.skills = db\&.Column(db\&.String(), nullable=False)\fC [static]\fP"

.PP
Definition at line 271 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
