.TH "sms.config" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.config
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbasedir\fP = os\&.path\&.abspath(os\&.path\&.dirname(__file__))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sms\&.config\&.basedir = os\&.path\&.abspath(os\&.path\&.dirname(__file__))"

.PP
Definition at line 2 of file config\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
