.TH "sms.sms_calendar.routes" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.sms_calendar.routes
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Response \fBfavicon\fP ()"
.br
.ti -1c
.RI "def \fBcalendar\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms_calendar\fP = Blueprint('sms_calendar', __name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def sms\&.sms_calendar\&.routes\&.calendar ()"

.PP
Definition at line 17 of file routes\&.py\&.
.SS " Response sms\&.sms_calendar\&.routes\&.favicon ()"

.PP
Definition at line 10 of file routes\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "sms\&.sms_calendar\&.routes\&.sms_calendar = Blueprint('sms_calendar', __name__)"

.PP
Definition at line 7 of file routes\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
