.TH "sms.posts.routes" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sms.posts.routes
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBnew_post\fP ()"
.br
.ti -1c
.RI "def \fBpost\fP (post_id)"
.br
.ti -1c
.RI "def \fBupdate_post\fP (post_id)"
.br
.ti -1c
.RI "def \fBdelete_post\fP (post_id)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBposts\fP = Blueprint('posts', __name__)"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def sms\&.posts\&.routes\&.delete_post ( post_id)"

.PP
Definition at line 51 of file routes\&.py\&.
.SS "def sms\&.posts\&.routes\&.new_post ()"

.PP
Definition at line 12 of file routes\&.py\&.
.SS "def sms\&.posts\&.routes\&.post ( post_id)"

.PP
Definition at line 25 of file routes\&.py\&.
.SS "def sms\&.posts\&.routes\&.update_post ( post_id)"

.PP
Definition at line 32 of file routes\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "sms\&.posts\&.routes\&.methods"

.PP
Definition at line 10 of file routes\&.py\&.
.SS "sms\&.posts\&.routes\&.posts = Blueprint('posts', __name__)"

.PP
Definition at line 7 of file routes\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
