.TH "USERS" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USERS \- The '\fBUSERS\fP' package contains all routes, forms, and utils that are specific for users according to their roles and requires login\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The '\fBUSERS\fP' package contains all routes, forms, and utils that are specific for users according to their roles and requires login\&. 

Mainly, the '\fBUSERS\fP' package contain user-related routes and forms such as 'Login', 'Account', etc\&.\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
