.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/users/utils.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/users/utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.users\&.utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsms\&.users\&.utils\&.save_picture\fP (form_picture)"
.br
.ti -1c
.RI "def \fBsms\&.users\&.utils\&.send_reset_email\fP (user)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
