.TH "C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/uwsgi.py" 3 "Sat Dec 28 2019" "Version 1.2.0" "SMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/CODE/PROJECTS/SMS/sms/sms_calendar/uwsgi.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsms\&.sms_calendar\&.uwsgi\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsms\&.sms_calendar\&.uwsgi\&.app\fP = flask_app\&.create_app()"
.br
.ti -1c
.RI "\fBsms\&.sms_calendar\&.uwsgi\&.debug\fP"
.br
.ti -1c
.RI "\fBsms\&.sms_calendar\&.uwsgi\&.host\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SMS from the source code\&.
